name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - kuuh
    paths-ignore:
      - "README*.md"
      - "fastlane/**"
      - "assets/**"
      - ".github/**/*.md"

jobs:
  debug-builds:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: gradle/actions/wrapper-validation@v5
      - uses: actions/setup-python@v6
        with:
          python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified

      - name: Retrieve Commit Info
        run: |
          cd .github
          curl https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }} > commit.json
          cd ..

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: 17
          distribution: "temurin"
          cache: "gradle"

      - name: Compile
        run: |
          ./gradlew assembleKuuh

      - name: Sign Apk
        continue-on-error: false
        id: sign_apk
        uses: ilharp/sign-android-release@v2
        with:
          releaseDir: app/build/outputs/apk/kuuh
          signingKey: ${{ secrets.ANDROID_SIGNING_KEY }}
          keyAlias: ${{ secrets.ANDROID_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}

      - name: Rename Apk
        id: rename_apk
        run: |
          mv app/build/outputs/apk/kuuh/app-arm64-v8a-kuuh-unsigned-signed.apk LibreTubeKuuh-arm64-v8a.apk
      
      - name: Upload APK
        uses: actions/upload-artifact@v6
        with:
          name: LibreTubeKuuh-arm64-v8a.apk
          path: ./*.apk


